--------------------------------------------------------
--  파일이 생성됨 - 목요일-1월-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "STARBUCKS"."ADMINS" 
   (	"ID" NUMBER, 
	"LOGIN" VARCHAR2(24 BYTE), 
	"PW" VARCHAR2(24 BYTE), 
	"NAME" VARCHAR2(24 BYTE), 
	"REG_DAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STARBUCKS"."ADMINS"."ID" IS '관리번호';
   COMMENT ON COLUMN "STARBUCKS"."ADMINS"."LOGIN" IS '아이디';
   COMMENT ON COLUMN "STARBUCKS"."ADMINS"."PW" IS '비밀번호';
   COMMENT ON COLUMN "STARBUCKS"."ADMINS"."NAME" IS '이름';
   COMMENT ON COLUMN "STARBUCKS"."ADMINS"."REG_DAY" IS '등록일';
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "STARBUCKS"."MEMBERS" 
   (	"ID" NUMBER, 
	"LOGIN" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"GENDER" NUMBER DEFAULT 1, 
	"BIRTH" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."ID" IS '회원번호';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."LOGIN" IS '아이디';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."PW" IS '비밀번호';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."NAME" IS '이름
';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."GENDER" IS '성별';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."PHONE" IS '핸드폰번호';
   COMMENT ON COLUMN "STARBUCKS"."MEMBERS"."EMAIL" IS '이메일';
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "STARBUCKS"."ORDERS" 
   (	"ID" NUMBER, 
	"ORDER_NUMBER" CHAR(10 BYTE), 
	"MEMBER_LOGIN" VARCHAR2(32 BYTE), 
	"PRODUCT_NAME" VARCHAR2(40 BYTE), 
	"QUANTITY" VARCHAR2(20 BYTE), 
	"TOTAL_PRICE" VARCHAR2(20 BYTE), 
	"ORDERED_TIME" DATE, 
	"ORDER_STATUS" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."ID" IS '관리번호';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."ORDER_NUMBER" IS '주문번호';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."MEMBER_LOGIN" IS '회원아이디';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."PRODUCT_NAME" IS '상품이름';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."QUANTITY" IS '상품수량';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."TOTAL_PRICE" IS '총가격';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."ORDERED_TIME" IS '주문일시';
   COMMENT ON COLUMN "STARBUCKS"."ORDERS"."ORDER_STATUS" IS '주문상태';
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "STARBUCKS"."PRODUCTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(48 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"IMAGE_PATH" VARCHAR2(512 BYTE), 
	"PRICE" NUMBER DEFAULT 1000, 
	"HOT" NUMBER DEFAULT 1, 
	"REG_DAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."ID" IS '관리번호';
   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."NAME" IS '상품이름';
   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."IMAGE_PATH" IS '이미지경로';
   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."PRICE" IS '상품가격';
   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."HOT" IS 'HOT/ICE';
   COMMENT ON COLUMN "STARBUCKS"."PRODUCTS"."REG_DAY" IS '상품출시일';
REM INSERTING into STARBUCKS.ADMINS
SET DEFINE OFF;
Insert into STARBUCKS.ADMINS (ID,LOGIN,PW,NAME,REG_DAY) values (1,'admin','1234','사장',to_date('20/11/03','RR/MM/DD'));
REM INSERTING into STARBUCKS.MEMBERS
SET DEFINE OFF;
Insert into STARBUCKS.MEMBERS (ID,LOGIN,PW,NAME,GENDER,BIRTH,PHONE,EMAIL) values (37,'admin','1234','관리자',1,'19920207','01094545474','admin@naver.com');
Insert into STARBUCKS.MEMBERS (ID,LOGIN,PW,NAME,GENDER,BIRTH,PHONE,EMAIL) values (36,'starbucks12','1234','홍길동',1,'19901010','01038986359','starbucks12naver.com');
Insert into STARBUCKS.MEMBERS (ID,LOGIN,PW,NAME,GENDER,BIRTH,PHONE,EMAIL) values (13,'kj941225','1234','김지호',1,'19941225','01012341231','kj941225@naver.com');
Insert into STARBUCKS.MEMBERS (ID,LOGIN,PW,NAME,GENDER,BIRTH,PHONE,EMAIL) values (3,'dlaehdgh12','1234','임동호',1,'19920101','01011111111','dlaehdgh12@naver.com');
Insert into STARBUCKS.MEMBERS (ID,LOGIN,PW,NAME,GENDER,BIRTH,PHONE,EMAIL) values (38,'admin1','1234','관리자1',1,'20201113','01012341234','admin1@naver.com');
REM INSERTING into STARBUCKS.ORDERS
SET DEFINE OFF;
Insert into STARBUCKS.ORDERS (ID,ORDER_NUMBER,MEMBER_LOGIN,PRODUCT_NAME,QUANTITY,TOTAL_PRICE,ORDERED_TIME,ORDER_STATUS) values (31,'SBSBN3105U','admin','녹차생크림케이크','1','3500',to_date('20/11/13','RR/MM/DD'),3);
Insert into STARBUCKS.ORDERS (ID,ORDER_NUMBER,MEMBER_LOGIN,PRODUCT_NAME,QUANTITY,TOTAL_PRICE,ORDERED_TIME,ORDER_STATUS) values (32,'SBSBN3105U','admin','슈크림가득바움쿠헨','1','4000',to_date('20/11/13','RR/MM/DD'),3);
Insert into STARBUCKS.ORDERS (ID,ORDER_NUMBER,MEMBER_LOGIN,PRODUCT_NAME,QUANTITY,TOTAL_PRICE,ORDERED_TIME,ORDER_STATUS) values (33,'SBSBN3105U','admin','블루베리쿠키치즈케이크','2','8000',to_date('20/11/13','RR/MM/DD'),3);
REM INSERTING into STARBUCKS.PRODUCTS
SET DEFINE OFF;
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (41,'아이스아메리카노','Coffee','아이스아메리카노.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (42,'아이스카라멜마키아또','Coffee','아이스카라멜마키아또.jpg',5000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (43,'에스프레소','Coffee','에스프레소.jpg',4000,1,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (44,'카푸치노','Coffee','카푸치노.jpg',4500,1,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (45,'콜드브루','Coffee','콜드브루.jpg',4500,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (46,'아이스카페라떼','Coffee','아이스카페라떼.jpg',4500,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (47,'아이스카페모카','Coffee','아이스카페모카.jpg',5000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (48,'카페모카','Coffee','카페모카.jpg',5000,1,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (49,'돌체라떼','Coffee','돌체라떼.jpg',5000,1,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (40,'카페아메리카노','Coffee','카페아메리카노.jpg',3500,1,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (50,'유자민트티','Beverage','유자민트티.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (51,'제주별빛애플주스','Beverage','제주별빛애플주스.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (52,'제주유기농녹차','Beverage','제주유기농녹차.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (53,'쿨라임피지오','Beverage','쿨라임피지오.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (54,'핑크자몽피지오','Beverage','핑크자몽피지오.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (55,'딸기주스','Beverage','딸기주스.jpg',3000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (56,'라임패션티','Beverage','라임패션티.jpg',3000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (57,'블루베리요거트','Beverage','블루베리요거트.jpg',3500,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (58,'수박주스','Beverage','수박주스.jpg',3000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (59,'녹차생크림케이크','Dessert','녹차생크림케이크.jpg',3500,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (60,'레드벨벳크림케이크','Dessert','레드벨벳크림케이크.jpg',3500,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (61,'번트치즈케이크','Dessert','번트치즈케이크.jpg',3000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (62,'블루베리쿠키치즈케이크','Dessert','블루베리쿠키치즈케이크.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (63,'슈크림가득바움쿠헨','Dessert','슈크림가득바움쿠헨.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (64,'얼그레이밀크케이크','Dessert','얼그레이밀크케이크.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (65,'티라미수케이크','Salad','티라미수케이크.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (66,'로스트치킨샐러드','Salad','로스트치킨샐러드.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (67,'쉬림프코코넛샐러드','Salad','쉬림프코코넛샐러드.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (68,'에그아보카도샐러드','Salad','에그아보카도샐러드.jpg',4000,2,to_date('20/11/05','RR/MM/DD'));
Insert into STARBUCKS.PRODUCTS (ID,NAME,CATEGORY,IMAGE_PATH,PRICE,HOT,REG_DAY) values (69,'치킨텐더콥샐러드','Salad','치킨텐더콥샐러드.jpg',4500,2,to_date('20/11/05','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index ADMINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."ADMINS_PK" ON "STARBUCKS"."ADMINS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_ADMINS_LOGIN
--------------------------------------------------------

  CREATE INDEX "STARBUCKS"."UQ_ADMINS_LOGIN" ON "STARBUCKS"."ADMINS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."MEMBERS_PK" ON "STARBUCKS"."MEMBERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_MEMBERS_LOGIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."UQ_MEMBERS_LOGIN" ON "STARBUCKS"."MEMBERS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."ORDERS_PK" ON "STARBUCKS"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_PRODCTS_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."UQ_PRODCTS_NAME" ON "STARBUCKS"."PRODUCTS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."PRODUCTS_PK" ON "STARBUCKS"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."ADMINS" ADD CONSTRAINT "ADMINS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STARBUCKS"."ADMINS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."MEMBERS" ADD CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STARBUCKS"."MEMBERS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."MEMBERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."MEMBERS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."MEMBERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."MEMBERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."MEMBERS" ADD CONSTRAINT "UQ_MEMBERS_LOGIN" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."ORDERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."ORDERS" MODIFY ("MEMBER_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STARBUCKS"."ORDERS" ADD CONSTRAINT "UQ_ORDERS_ORDERNUMBER" UNIQUE ("ORDER_NUMBER") DISABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "STARBUCKS"."PRODUCTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."PRODUCTS" ADD CONSTRAINT "UQ_PRODUCTS_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."ORDERS" ADD CONSTRAINT "MEMBERS_LOGIN_FK" FOREIGN KEY ("MEMBER_LOGIN")
	  REFERENCES "STARBUCKS"."MEMBERS" ("LOGIN") ENABLE;
  ALTER TABLE "STARBUCKS"."ORDERS" ADD CONSTRAINT "PRODUCT_NAME_FK" FOREIGN KEY ("PRODUCT_NAME")
	  REFERENCES "STARBUCKS"."PRODUCTS" ("NAME") ENABLE;
